apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fhhmh61wz-go 
  janus-idp.io/tekton: fhhmh61wz-go
  backstage.io/kubernetes-id: fhhmh61wz-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fhhmh61wz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml