apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fhhmh61wz-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-go:6b1de6477cbb2131d5cffdf461551bc2c852f9ed@sha256:dfc6345b2ff53b2607589338d42053dae3c35a0fbf5ee99b32c00bd3638a7893
          name: container-image
